// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentSettings() {
  return window['go']['main']['App']['GetCurrentSettings']();
}

export function GetCurrentSnippets() {
  return window['go']['main']['App']['GetCurrentSnippets']();
}
