// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCurrentSettings():Promise<main.AppConfig>;

export function GetCurrentSnippets():Promise<Array<main.Snippet>>;
